name: .NET
on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Test
      run: dotnet test --verbosity normal

    - name: Build
      run: dotnet build --no-restore
      
    - name: Pack
      run: dotnet pack --no-restore
    - name: Publish NuGet
        
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: RestMongo/RestMongo.csproj
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
          
